/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as WhyEvergreenRouteImport } from './routes/why-evergreen'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyEvergreenRoute = WhyEvergreenRouteImport.update({
  id: '/why-evergreen',
  path: '/why-evergreen',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/applications': typeof ApplicationsRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRoute
  '/sustainability': typeof SustainabilityRoute
  '/why-evergreen': typeof WhyEvergreenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/applications': typeof ApplicationsRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRoute
  '/sustainability': typeof SustainabilityRoute
  '/why-evergreen': typeof WhyEvergreenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/applications': typeof ApplicationsRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRoute
  '/sustainability': typeof SustainabilityRoute
  '/why-evergreen': typeof WhyEvergreenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/applications'
    | '/contact'
    | '/products'
    | '/sustainability'
    | '/why-evergreen'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/applications'
    | '/contact'
    | '/products'
    | '/sustainability'
    | '/why-evergreen'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/applications'
    | '/contact'
    | '/products'
    | '/sustainability'
    | '/why-evergreen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApplicationsRoute: typeof ApplicationsRoute
  ContactRoute: typeof ContactRoute
  ProductsRoute: typeof ProductsRoute
  SustainabilityRoute: typeof SustainabilityRoute
  WhyEvergreenRoute: typeof WhyEvergreenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-evergreen': {
      id: '/why-evergreen'
      path: '/why-evergreen'
      fullPath: '/why-evergreen'
      preLoaderRoute: typeof WhyEvergreenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApplicationsRoute: ApplicationsRoute,
  ContactRoute: ContactRoute,
  ProductsRoute: ProductsRoute,
  SustainabilityRoute: SustainabilityRoute,
  WhyEvergreenRoute: WhyEvergreenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
